// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mixbayes_gibbs_cpp
List mixbayes_gibbs_cpp(std::string family, const arma::mat& X, const arma::vec& y, const arma::ivec& event, const arma::mat& Z, const arma::ivec& safe, List priors, List init, int n_iter, int n_burnin, int thin, int n_pilot, int pilot_iter, bool collapse_theta, bool verbose, int pre_orient, double orient_tol);
RcppExport SEXP _postlink_mixbayes_gibbs_cpp(SEXP familySEXP, SEXP XSEXP, SEXP ySEXP, SEXP eventSEXP, SEXP ZSEXP, SEXP safeSEXP, SEXP priorsSEXP, SEXP initSEXP, SEXP n_iterSEXP, SEXP n_burninSEXP, SEXP thinSEXP, SEXP n_pilotSEXP, SEXP pilot_iterSEXP, SEXP collapse_thetaSEXP, SEXP verboseSEXP, SEXP pre_orientSEXP, SEXP orient_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type safe(safeSEXP);
    Rcpp::traits::input_parameter< List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< List >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type n_pilot(n_pilotSEXP);
    Rcpp::traits::input_parameter< int >::type pilot_iter(pilot_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type collapse_theta(collapse_thetaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type pre_orient(pre_orientSEXP);
    Rcpp::traits::input_parameter< double >::type orient_tol(orient_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(mixbayes_gibbs_cpp(family, X, y, event, Z, safe, priors, init, n_iter, n_burnin, thin, n_pilot, pilot_iter, collapse_theta, verbose, pre_orient, orient_tol));
    return rcpp_result_gen;
END_RCPP
}
// ecr_two_cpp
LogicalVector ecr_two_cpp(const IntegerMatrix& z, int maxiter, double threshold, const IntegerVector& cols);
RcppExport SEXP _postlink_ecr_two_cpp(SEXP zSEXP, SEXP maxiterSEXP, SEXP thresholdSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(ecr_two_cpp(z, maxiter, threshold, cols));
    return rcpp_result_gen;
END_RCPP
}
// count_label2_cpp
double count_label2_cpp(const IntegerMatrix& z, const LogicalVector& swap, const IntegerVector& cols);
RcppExport SEXP _postlink_count_label2_cpp(SEXP zSEXP, SEXP swapSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type swap(swapSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(count_label2_cpp(z, swap, cols));
    return rcpp_result_gen;
END_RCPP
}
// swap_rows_cpp
IntegerMatrix swap_rows_cpp(const IntegerMatrix& z, const LogicalVector& swap);
RcppExport SEXP _postlink_swap_rows_cpp(SEXP zSEXP, SEXP swapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type swap(swapSEXP);
    rcpp_result_gen = Rcpp::wrap(swap_rows_cpp(z, swap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_postlink_mixbayes_gibbs_cpp", (DL_FUNC) &_postlink_mixbayes_gibbs_cpp, 17},
    {"_postlink_ecr_two_cpp", (DL_FUNC) &_postlink_ecr_two_cpp, 4},
    {"_postlink_count_label2_cpp", (DL_FUNC) &_postlink_count_label2_cpp, 3},
    {"_postlink_swap_rows_cpp", (DL_FUNC) &_postlink_swap_rows_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_postlink(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
