# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
mixbayes_gibbs_cpp <- function(family, X, y, event, Z, safe, priors, init, n_iter, n_burnin, thin, n_pilot, pilot_iter, collapse_theta, verbose, pre_orient = 0L, orient_tol = 2.0) {
    .Call(`_postlink_mixbayes_gibbs_cpp`, family, X, y, event, Z, safe, priors, init, n_iter, n_burnin, thin, n_pilot, pilot_iter, collapse_theta, verbose, pre_orient, orient_tol)
}

#' @noRd
ecr_two_cpp <- function(z, maxiter, threshold, cols) {
    .Call(`_postlink_ecr_two_cpp`, z, maxiter, threshold, cols)
}

#' @noRd
count_label2_cpp <- function(z, swap, cols) {
    .Call(`_postlink_count_label2_cpp`, z, swap, cols)
}

#' @noRd
swap_rows_cpp <- function(z, swap) {
    .Call(`_postlink_swap_rows_cpp`, z, swap)
}

